### ISSUE TITLE
Bandpass red and blue limit

### ISSUE THREAD

**Issue by FedericoBerlfein** [GalSim-developers/GalSim-Euclid-Like#80]
Currently the blue and red limits for the VIS bandpass are adjusted manually to take into account that the PSF images do not cover parts of the bandpass wavelength range where the filter throughput is very small. These manual cuts are currently implemented in `euclidlike_imsim`, but maybe they should be implemented directly in the `euclidlike`? In addition, the cuts are hard coded, but the applied blue/red limits should probably be specified somewhere else (like `instrument_params.py)`. Documentation of these cuts is also needed. For the purposes of consistency as well, the effective wavelength of the bandpass is slightly different if you use the full bandpass vs the cut one, so we should also be consistent about which one we use.

This is a minor detail, but it should probably be discussed at some point.

**Comment by rmandelb** [comment]
This was closed by #87.
